# Travis CI settings

language: python

python:
  - '3.4'

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - py.test tests/
  - pylint tests/ spi.py  # Syntax validation